/* Aldercrest Reserve — standalone storefront prototype.
 * No backend, payments, accounts, tracking, or external dependencies.
 * Prices are integer cents. Never use this browser-controlled catalog to
 * authorize real orders; a production server must validate all order data.
 */
(() => {
  'use strict';
  const ICONS = {
    search: '<circle cx="10.8" cy="10.8" r="6.7"/><path d="m16 16 4.7 4.7"/>',
    heart: '<path d="M20.8 5.7a5.3 5.3 0 0 0-7.5 0L12 7l-1.3-1.3a5.3 5.3 0 0 0-7.5 7.5L12 22l8.8-8.8a5.3 5.3 0 0 0 0-7.5Z" transform="translate(1 0) scale(.91)"/>',
    bag: '<path d="M5 7.5h14l1 14H4l1-14Z"/><path d="M8 8V5a4 4 0 0 1 8 0v3"/>',
    arrow: '<path d="M3 12h17M14 6l6 6-6 6"/>',
    chevron: '<path d="m6 9 6 6 6-6"/>',
    sliders: '<path d="M4 7h6m4 0h6M4 17h10m4 0h2"/><circle cx="12" cy="7" r="2"/><circle cx="16" cy="17" r="2"/>',
    x: '<path d="m6 6 12 12M6 18 18 6"/>',
    plus: '<path d="M12 5v14M5 12h14"/>',
    minus: '<path d="M5 12h14"/>',
    check: '<path d="m4 12 5 5L20 6"/>',
    info: '<circle cx="12" cy="12" r="9"/><path d="M12 11v6M12 7h.01"/>',
    detail: '<path d="M12 2 20 6v6c0 5-8 10-8 10S4 17 4 12V6l8-4Z"/><path d="m8.5 11.5 2.5 2.5 4.5-5"/>',
    collection: '<path d="m12 2 10 5-10 5L2 7l10-5ZM2 12l10 5 10-5M2 17l10 5 10-5"/>',
    conversation: '<path d="M21 11a9 9 0 0 1-9 9c-1.5 0-2.7-.3-4-.8L3 21l1.8-4.8A9 9 0 1 1 21 11Z"/><path d="M8 11h.01M12 11h.01M16 11h.01"/>',
    download: '<path d="M12 3v12m-5-5 5 5 5-5M4 16v5h16v-5"/>'
  };
  const icon = name => `<svg class="icon" viewBox="0 0 24 24" aria-hidden="true">${ICONS[name] || ICONS.info}</svg>`;
  const $ = (selector, root = document) => root.querySelector(selector);
  const $$ = (selector, root = document) => [...root.querySelectorAll(selector)];
  const esc = value => String(value).replace(/[&<>"']/g, char => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
  const money = cents => new Intl.NumberFormat('en-US', {style:'currency', currency:'USD'}).format(cents / 100);
  const MAX_QUANTITY = 20;
  const STORAGE_KEY = 'aldercrest-reserve-demo-v1';

  // Fictional inventory. All content must be replaced and verified before launch.
  const PRODUCTS = [
    {id:'ar-g01',name:'1 oz gold round',subtitle:'Signature design · .9999 fine gold',categoryLabel:'Gold / bullion',categories:['gold'],metal:'gold',format:'round',variant:'signature',weight:'1 troy oz (sample)',purity:'.9999 fine gold (sample)',price:465000,added:12,description:'A classic gold format, with a clean design and a substantial presence. This demonstration listing illustrates how a bullion product could be presented.'},
    {id:'ar-s01',name:'1 oz silver round',subtitle:'Classic design · .999 fine silver',categoryLabel:'Silver / bullion',categories:['silver'],metal:'silver',format:'round',variant:'classic',weight:'1 troy oz (sample)',purity:'.999 fine silver (sample)',price:6800,added:11,description:'An understated silver round for the everyday collection. The artwork, specifications, and price shown here are examples, not verified inventory.'},
    {id:'ar-c01',name:'Collector’s silver dollar',subtitle:'Heritage-inspired · sample collectible',categoryLabel:'Collectible coins',categories:['coins','silver'],metal:'silver',format:'round',variant:'heritage',weight:'1 troy oz (sample)',purity:'Illustrative specification',price:12500,added:10,description:'A heritage-inspired concept piece with a distinctive profile. This is not an actual historical, legal-tender, or professionally graded coin listing.'},
    {id:'ar-s05',name:'5 oz silver bar',subtitle:'Bar format · .999 fine silver',categoryLabel:'Silver / bars',categories:['silver'],metal:'silver',format:'bar',variant:'5',weight:'5 troy oz (sample)',purity:'.999 fine silver (sample)',price:34000,added:9,description:'A simple, sculptural bar format in silver. The sample presentation shows how metal content, weight, and individual product details can be made easy to find.'},
    {id:'ar-g10',name:'1/10 oz gold round',subtitle:'Fractional gold · signature design',categoryLabel:'Gold / fractional',categories:['gold'],metal:'gold',format:'round',variant:'fractional',weight:'1/10 troy oz (sample)',purity:'.9999 fine gold (sample)',price:49500,added:8,description:'A smaller format with the same thoughtful presentation. Fractional gold appears here as an example category; this is not a current market quote.'},
    {id:'ar-s10',name:'10 oz silver bar',subtitle:'Bar format · .999 fine silver',categoryLabel:'Silver / bars',categories:['silver'],metal:'silver',format:'bar',variant:'10',weight:'10 troy oz (sample)',purity:'.999 fine silver (sample)',price:65000,added:7,description:'A larger silver-bar concept with a straightforward, weight-led design. This item is included to demonstrate product variations and catalog filters.'},
    {id:'ar-c02',name:'Proof-style silver round',subtitle:'Mirror-inspired finish · concept piece',categoryLabel:'Collectible coins',categories:['coins','silver'],metal:'silver',format:'round',variant:'proof',weight:'1 troy oz (sample)',purity:'.999 fine silver (sample)',price:8900,added:6,description:'Reflective surfaces and a restrained emblem, imagined as a collector-focused silver round. No actual proof designation, mint, or grade is represented.'},
    {id:'ar-set01',name:'The silver trio',subtitle:'Three complementary sample rounds',categoryLabel:'Sets & collections',categories:['sets','silver'],metal:'silver',format:'set',variant:'trio',weight:'3 × 1 troy oz (sample)',purity:'.999 fine silver (sample)',price:24500,added:5,description:'A three-piece concept collection with different silver designs. A sample set demonstrates how complementary products can be grouped in the storefront.'},
    {id:'ar-g25',name:'1/4 oz gold round',subtitle:'Fractional gold · .9999 fine',categoryLabel:'Gold / fractional',categories:['gold'],metal:'gold',format:'round',variant:'quarter',weight:'1/4 troy oz (sample)',purity:'.9999 fine gold (sample)',price:122500,added:4,description:'A quarter-ounce gold concept, designed to sit between the smaller and full-ounce sample listings. Artwork and pricing are for demonstration only.'},
    {id:'ar-set02',name:'Gold & silver discovery set',subtitle:'A two-metal collection concept',categoryLabel:'Sets & collections',categories:['sets','gold','silver'],metal:'mixed',format:'set',variant:'mixed',weight:'1/10 oz gold + 1 oz silver (sample)',purity:'Illustrative specifications',price:59000,added:3,description:'A contrasting pair that brings both metal categories into one sample listing. No physical set is offered for sale through this demonstration.'},
    {id:'ar-sb01',name:'1 oz silver bar',subtitle:'Compact bar · .999 fine silver',categoryLabel:'Silver / bars',categories:['silver'],metal:'silver',format:'bar',variant:'1',weight:'1 troy oz (sample)',purity:'.999 fine silver (sample)',price:7500,added:2,description:'A compact silver-bar concept with simple geometric detailing. Replace the sample artwork with images of actual inventory before publishing a live product.'},
    {id:'ar-c03',name:'Heritage silver round',subtitle:'Landscape design · sample collectible',categoryLabel:'Collectible coins',categories:['coins','silver'],metal:'silver',format:'round',variant:'landscape',weight:'1 troy oz (sample)',purity:'.999 fine silver (sample)',price:9800,added:1,description:'A landscape-inspired silver concept with layered engraving-style detail. This fictional round is not associated with any government mint or grading service.'}
  ];
  const productById = new Map(PRODUCTS.map(product => [product.id, product]));
  const state = {cart:{}, favorites:[], category:'all', search:'', sort:'featured', price:'all', savedOnly:false};
  let toastTimer, artCounter = 0, detailQuantity = 1, currentProductId = null;
  let lastInquiry = '', lastOrder = null;
  const ids = prefix => `${prefix}-${++artCounter}`;

  // Original, generic SVG concept artwork. These are not product photographs.
  function coinBody(metal = 'gold', variant = 'signature', stamp = '1 OZ') {
    const id = ids('coin');
    const gold = metal === 'gold';
    const colors = gold ? ['#f9e8a4','#cda855','#f3d985','#b18b37','#edcf78','#8b692c'] : ['#fbfbf4','#b3b9b0','#edf0e9','#8e9b90','#d9ded5','#65786d'];
    const dark = gold ? '#8f692c' : '#718276';
    const light = gold ? '#fff0b5' : '#fffef7';
    const marks = Array.from({length:100}, (_,i) => `<path d="M120 27v4.4" transform="rotate(${i*3.6} 120 120)" stroke="${dark}" stroke-width="1" opacity=".67"/>`).join('');
    const wreath = Array.from({length:8},(_,i)=>{const y=159-i*8,x=64-Math.sin(i/8*Math.PI)*8;return `<path d="M${x} ${y}q-9-2-8-10 9 1 9 8m0 0q8-4 7-10-8 3-8 10"/>`}).join('');
    const center = ['heritage','landscape'].includes(variant) ? `<g fill="none" stroke="${dark}" stroke-width="1.3" opacity=".85"><path d="m61 142 33-43 22 26 18-33 49 50H61Z"/><path d="m94 99 4 21 9-7m27-21-8 29 10-7 11 12M65 148h112M73 154h97"/><circle cx="161" cy="94" r="9"/><path d="m89 159 5-13 5 13M112 162l5-15 5 15M140 163l5-20 6 20"/></g>` : variant === 'proof' ? `<g fill="none" stroke="${dark}" opacity=".8"><path d="m120 79 34 61h-68l34-61Z" stroke-width="2"/><path d="m120 96 24 44M120 96l-24 44M99 118h42M120 140v19M102 159h36" stroke-width="1.6"/></g>` : `<text x="120" y="140" font-family="Georgia,serif" font-size="62" fill="${dark}" opacity=".87" text-anchor="middle" letter-spacing="-4">${gold?'Au':'Ag'}</text><text x="120" y="157" font-family="Arial,sans-serif" font-size="5.5" letter-spacing="2.3" fill="${dark}" text-anchor="middle">${gold?'FINE GOLD':'FINE SILVER'}</text>`;
    return `<g><defs><radialGradient id="${id}-edge" cx="32%" cy="21%"><stop offset="0" stop-color="${colors[0]}"/><stop offset=".47" stop-color="${colors[1]}"/><stop offset=".75" stop-color="${colors[2]}"/><stop offset="1" stop-color="${colors[3]}"/></radialGradient><linearGradient id="${id}-face" x1="0" y1="0" x2="1" y2="1"><stop stop-color="${colors[0]}"/><stop offset=".27" stop-color="${colors[1]}"/><stop offset=".48" stop-color="${colors[2]}"/><stop offset=".66" stop-color="${colors[1]}"/><stop offset=".9" stop-color="${colors[4]}"/><stop offset="1" stop-color="${colors[0]}"/></linearGradient><linearGradient id="${id}-light" x1="0" y1="0" x2="1" y2="1"><stop stop-color="#fff" stop-opacity=".38"/><stop offset=".43" stop-color="#fff" stop-opacity="0"/><stop offset=".51" stop-color="#fff" stop-opacity=".28"/><stop offset=".7" stop-color="#fff" stop-opacity="0"/></linearGradient><path id="${id}-top" d="M54 125a66 66 0 0 1 132 0"/><path id="${id}-bottom" d="M47 126a73 73 0 0 0 146 0"/></defs><circle cx="122" cy="125" r="96" fill="${colors[5]}"/><circle cx="120" cy="120" r="96" fill="url(#${id}-edge)" stroke="${colors[5]}" stroke-width=".6"/><circle cx="120" cy="120" r="91" fill="url(#${id}-face)" stroke="${light}" stroke-opacity=".75" stroke-width="1.3"/>${marks}<circle cx="120" cy="120" r="85.5" fill="none" stroke="${dark}" stroke-width=".8"/><circle cx="120" cy="120" r="82.5" fill="none" stroke="${light}" stroke-width=".8" opacity=".65"/><circle cx="120" cy="120" r="59" fill="none" stroke="${dark}" stroke-width=".7" opacity=".6"/><circle cx="120" cy="120" r="58" fill="none" stroke="${light}" stroke-width=".6" opacity=".55"/><text fill="${dark}" font-family="Georgia,serif" font-size="9.5" letter-spacing="2.7"><textPath href="#${id}-top" startOffset="50%" text-anchor="middle">ALDERCREST RESERVE</textPath></text><text fill="${dark}" font-family="Arial,sans-serif" font-size="7" letter-spacing="2"><textPath href="#${id}-bottom" startOffset="50%" text-anchor="middle">${esc(stamp)} · ${gold?'.9999 GOLD':'.999 SILVER'}</textPath></text><g fill="none" stroke="${dark}" stroke-width=".55" opacity=".55">${wreath}</g><g fill="none" stroke="${dark}" stroke-width=".55" opacity=".55" transform="translate(240 0) scale(-1 1)">${wreath}</g>${center}<path d="m45 99 3 2-1 4 3-2 3 2-1-4 3-2h-4l-1-4-1 4h-4Zm143 0 3 2-1 4 3-2 3 2-1-4 3-2h-4l-1-4-1 4h-4Z" fill="${dark}" opacity=".7"/><circle cx="120" cy="120" r="94" fill="url(#${id}-light)"/><path d="M34 98a88 88 0 0 1 153-36" fill="none" stroke="${light}" stroke-width="1.5" opacity=".65"/></g>`;
  }
  function barBody(metal = 'silver', ounces = '5') {
    const id = ids('bar'), gold = metal === 'gold';
    const c = gold ? ['#c7a251','#fff0b6','#e2c371','#8f692c','#f5e0a2'] : ['#a1afa5','#fcfcf5','#d9e1d7','#6c8076','#eef1e9'];
    return `<g><defs><linearGradient id="${id}-face" x1="0" y1="0" x2="1" y2=".6"><stop stop-color="${c[0]}"/><stop offset=".2" stop-color="${c[1]}"/><stop offset=".45" stop-color="${c[2]}"/><stop offset=".66" stop-color="${c[1]}"/><stop offset="1" stop-color="${c[0]}"/></linearGradient><linearGradient id="${id}-edge" x1="0" y1="0" x2="1" y2="1"><stop stop-color="${c[1]}"/><stop offset="1" stop-color="${c[3]}"/></linearGradient></defs><g transform="rotate(-12 120 120)"><path d="M67 35h104q10 0 10 10v159q0 12-12 12H68q-11 0-11-12V47q0-12 10-12Z" fill="${c[3]}"/><rect x="54" y="28" width="124" height="182" rx="13" fill="url(#${id}-edge)" stroke="${c[3]}" stroke-width=".8"/><rect x="59" y="32" width="114" height="172" rx="10" fill="url(#${id}-face)" stroke="${c[1]}" stroke-width="1"/><rect x="65" y="38" width="102" height="160" rx="7" fill="none" stroke="${c[3]}" stroke-width=".6" opacity=".48"/><g fill="none" stroke="${c[3]}" stroke-width="1.1" opacity=".76"><path d="m116 54 16 29H100l16-29Z"/><path d="m116 64 11 19M116 64l-11 19M106 73h20M116 83v8M108 91h16"/></g><text x="116" y="106" font-family="Georgia,serif" font-size="9.3" letter-spacing=".9" text-anchor="middle" fill="${c[3]}">ALDERCREST</text><text x="116" y="117" font-family="Arial,sans-serif" font-size="4.5" letter-spacing="2.8" text-anchor="middle" fill="${c[3]}">RESERVE</text><path d="M83 127h66" stroke="${c[3]}" stroke-width=".6" opacity=".65"/><text x="116" y="146" font-family="Georgia,serif" font-size="17" text-anchor="middle" fill="${c[3]}">${esc(ounces)} OZ</text><text x="116" y="159" font-family="Arial,sans-serif" font-size="6" letter-spacing="1.2" text-anchor="middle" fill="${c[3]}">${gold?'FINE GOLD .9999':'FINE SILVER .999'}</text><text x="116" y="182" font-family="monospace" font-size="6" letter-spacing="1.3" text-anchor="middle" fill="${c[3]}" opacity=".65">CONCEPT 001</text><path d="M68 33h96M60 43v149" stroke="white" stroke-opacity=".85" stroke-width="1.2"/></g></g>`;
  }
  function productArt(product) {
    let body = '';
    if (product.format === 'bar') body = `<g transform="translate(9 3)">${barBody(product.metal,product.variant)}</g>`;
    else if (product.format === 'set' && product.variant === 'mixed') body = `<g transform="translate(48 1) scale(.83)">${coinBody('silver','classic')}</g><g transform="translate(-4 50) scale(.78)">${coinBody('gold','fractional','1/10 OZ')}</g>`;
    else if (product.format === 'set') body = `<g transform="translate(46 -6) scale(.73)">${coinBody('silver','classic')}</g><g transform="translate(79 66) scale(.69)">${coinBody('silver','proof')}</g><g transform="translate(-9 52) scale(.76)">${coinBody('silver','heritage')}</g>`;
    else {const stamp = product.variant==='fractional'?'1/10 OZ':product.variant==='quarter'?'1/4 OZ':'1 OZ';body=`<g transform="translate(9 3)">${coinBody(product.metal,product.variant,stamp)}</g>`;}
    return `<svg viewBox="0 0 260 250" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Concept illustration: ${esc(product.name)}"><ellipse cx="134" cy="227" rx="74" ry="8" fill="#67715a" opacity=".065"/>${body}</svg>`;
  }
  function buildHeroArt() {
    const id=ids('hero');
    return `<svg viewBox="0 0 680 570" xmlns="http://www.w3.org/2000/svg" aria-hidden="true"><defs><linearGradient id="${id}-front" x1="0" y1="0" x2="1" y2="1"><stop stop-color="#4a5e49"/><stop offset="1" stop-color="#253c30"/></linearGradient><linearGradient id="${id}-top" x1="0" y1="0" x2="1" y2="1"><stop stop-color="#7f8970"/><stop offset="1" stop-color="#4e6249"/></linearGradient><linearGradient id="${id}-stone" x1="0" y1="0" x2="1" y2="1"><stop stop-color="#d5c9ac"/><stop offset="1" stop-color="#b5a786"/></linearGradient><filter id="${id}-shadow" x="-30%" y="-30%" width="170%" height="180%"><feDropShadow dx="5" dy="13" stdDeviation="9" flood-color="#2f3021" flood-opacity=".2"/></filter></defs><ellipse cx="364" cy="464" rx="247" ry="45" fill="#7e7454" opacity=".09"/><ellipse cx="388" cy="474" rx="202" ry="17" fill="#756e50" opacity=".08"/><path d="m249 288 166-70 199 98-173 78-192-106Z" fill="url(#${id}-top)"/><path d="m249 288 192 106v126L249 414V288Z" fill="url(#${id}-front)"/><path d="m441 394 173-78v125L441 520V394Z" fill="#2b4233"/><path d="m250 289 191 106 172-78" fill="none" stroke="#c0c6a2" opacity=".25"/><path d="m82 381 144-58 174 99-146 69L82 381Z" fill="#e0d6bf"/><path d="m82 381 172 110v35L82 415v-34Z" fill="url(#${id}-stone)"/><path d="m254 491 146-69v36l-146 68v-35Z" fill="#ada180"/><path d="m83 382 171 109 145-68" fill="none" stroke="#f6eedb" stroke-width="1.3" opacity=".7"/><g filter="url(#${id}-shadow)"><g transform="translate(328 76) rotate(14 135 135) scale(1.12)">${coinBody('silver','heritage')}</g><g transform="translate(175 169) rotate(-13 130 130) scale(1.23)">${coinBody('gold','signature')}</g><g transform="translate(58 315) rotate(9 90 80) scale(.83)">${barBody('silver','5')}</g></g><path d="M548 189h31m-15-15v30" stroke="#a79870" stroke-width=".7" opacity=".55"/><path d="M101 220h15m-7-8v16" stroke="#a79870" stroke-width=".7" opacity=".45"/><circle cx="559" cy="115" r="2" fill="#b6ab8b" opacity=".5"/></svg>`;
  }
  function buildSellArt() {
    return `<svg viewBox="0 0 510 320" xmlns="http://www.w3.org/2000/svg" aria-hidden="true"><circle cx="248" cy="158" r="139" fill="none" stroke="#c9d2b3" stroke-opacity=".11"/><circle cx="248" cy="158" r="120" fill="none" stroke="#c9d2b3" stroke-opacity=".07"/><ellipse cx="261" cy="265" rx="155" ry="18" fill="#0d2118" opacity=".2"/><g transform="translate(251 29) rotate(15 90 90) scale(.87)">${coinBody('silver','proof')}</g><g transform="translate(79 56) rotate(-16 100 100) scale(.92)">${coinBody('gold','signature')}</g><g transform="translate(194 126) rotate(7 90 90) scale(.75)">${coinBody('silver','heritage')}</g></svg>`;
  }
  function initIcons(root = document) {$$('[data-icon]',root).forEach(node => {node.innerHTML=icon(node.dataset.icon);});}
  function loadState() {
    try {
      const saved=JSON.parse(localStorage.getItem(STORAGE_KEY)||'null');
      if (!saved || typeof saved !== 'object') return;
      if(saved.cart && typeof saved.cart === 'object' && !Array.isArray(saved.cart)) {
        for(const [id,qty] of Object.entries(saved.cart)) {
          if(productById.has(id)&&Number.isInteger(qty)&&qty>=1&&qty<=MAX_QUANTITY) state.cart[id]=qty;
        }
      }
      if(Array.isArray(saved.favorites)) state.favorites=[...new Set(saved.favorites.filter(id=>typeof id==='string'&&productById.has(id)))];
    } catch { /* Private browsing or malformed demo data: use clean in-memory state. */ }
  }
  function persist(){try{localStorage.setItem(STORAGE_KEY,JSON.stringify({cart:state.cart,favorites:state.favorites}));}catch{/* The store still works without local persistence. */}}
  function notify(message){$('#toast').textContent=message;$('#toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('visible'),3100);}
  function cartCount(){return Object.values(state.cart).reduce((sum,qty)=>sum+qty,0);}
  function subtotal(){return Object.entries(state.cart).reduce((sum,[id,qty])=>sum+productById.get(id).price*qty,0);}
  function updateCounts(){const count=cartCount();$('#cartCount').textContent=count;$('#cartTitleCount').textContent=count;$('#cartTrigger').setAttribute('aria-label',`Open bag, ${count} ${count===1?'item':'items'}`);$('#favoriteCount').textContent=state.favorites.length;$('#favoriteCount').hidden=!state.favorites.length;$('#favoritesTrigger').setAttribute('aria-label',`View saved pieces, ${state.favorites.length} saved`);}
  function openDialog(id){const dialog=document.getElementById(id);if(!dialog)return;if(id==='cartDialog')renderCart();if(id==='filterDialog')syncFilterForm();$$('dialog[open]').forEach(el=>el.close());dialog.showModal();}
  function closeDialogFrom(node){node.closest('dialog')?.close();}
  function resetFilters(){state.category='all';state.search='';state.price='all';state.savedOnly=false;state.sort='featured';$('#productSearch').value='';$('#sortSelect').value='featured';renderCatalog();}
  function chooseCategory(category){state.category=category;state.savedOnly=false;renderCatalog();}
  function matchesPrice(price){switch(state.price){case'under100':return price<10000;case'100to500':return price>=10000&&price<50000;case'500to1500':return price>=50000&&price<150000;case'1500plus':return price>=150000;default:return true;}}
  function filteredProducts(){const query=state.search.trim().toLowerCase();const list=PRODUCTS.filter(p=>(state.category==='all'||p.categories.includes(state.category))&&(!state.savedOnly||state.favorites.includes(p.id))&&matchesPrice(p.price)&&(!query||`${p.name} ${p.subtitle} ${p.categoryLabel} ${p.metal}`.toLowerCase().includes(query)));switch(state.sort){case'price-asc':list.sort((a,b)=>a.price-b.price);break;case'price-desc':list.sort((a,b)=>b.price-a.price);break;case'name':list.sort((a,b)=>a.name.localeCompare(b.name));break;case'newest':list.sort((a,b)=>b.added-a.added);break;}return list;}
  function productCard(p){const saved=state.favorites.includes(p.id);return `<article class="product-card" data-tone="${p.metal}" data-product-id="${p.id}"><div class="product-image-wrap"><span class="product-badge">SAMPLE LISTING</span><button type="button" class="favorite-button" data-save="${p.id}" aria-pressed="${saved}" aria-label="${saved?'Unsave':'Save'} ${esc(p.name)}">${icon('heart')}</button><button class="product-open" type="button" data-product="${p.id}" aria-label="View ${esc(p.name)}">${productArt(p)}</button></div><div class="product-info"><div class="product-category">${esc(p.categoryLabel)}</div><h3 class="product-name"><button type="button" data-product="${p.id}">${esc(p.name)}</button></h3><p class="product-description">${esc(p.subtitle)}</p><div class="product-bottom"><span class="product-price">${money(p.price)} <small>USD</small></span><button class="add-button" type="button" data-add="${p.id}" aria-label="Add ${esc(p.name)} to demo bag" title="Add to demo bag">${icon('plus')}</button></div></div></article>`;}
  function renderCatalog(){const list=filteredProducts();$('#productGrid').innerHTML=list.map(productCard).join('');$('#emptyState').hidden=list.length>0;$('#resultCount').textContent=`${list.length} ${list.length===1?'piece':'pieces'}`;$$('[data-category]').forEach(button=>{const active=button.dataset.category===state.category;button.classList.toggle('selected',active);button.setAttribute('aria-pressed',String(active));});let chips='';if(state.savedOnly)chips+=`<button type="button" class="active-chip" data-clear-saved>Saved ${icon('x')}</button>`;if(state.price!=='all')chips+=`<button type="button" class="active-chip" data-clear-price>Price filter ${icon('x')}</button>`;$('#activeFilters').innerHTML=chips;const count=Number(state.savedOnly)+Number(state.price!=='all');$('#filterCount').textContent=count;$('#filterCount').hidden=!count;updateCounts();}
  function toggleFavorite(id){if(!productById.has(id))return;const index=state.favorites.indexOf(id);if(index>=0)state.favorites.splice(index,1);else state.favorites.push(id);persist();renderCatalog();if($('#productDialog').open&&currentProductId===id)renderDetail(id);notify(index>=0?'Piece removed from your saved collection.':'Piece saved to this browser.');}
  function addToCart(id,quantity=1){if(!productById.has(id))return;const current=state.cart[id]||0;const added=Math.min(Math.max(1,quantity),MAX_QUANTITY-current);if(added<=0){notify(`Demo limit: ${MAX_QUANTITY} per listing.`);return;}state.cart[id]=current+added;persist();updateCounts();if($('#cartDialog').open)renderCart();notify(`${added===1?'Added to your demo bag':`${added} pieces added to your demo bag`}.`);}
  function changeQuantity(id,change){if(!state.cart[id])return;const next=state.cart[id]+change;if(next>MAX_QUANTITY){notify(`Demo limit: ${MAX_QUANTITY} per listing.`);return;}if(next<=0)delete state.cart[id];else state.cart[id]=next;persist();updateCounts();renderCart();}
  function renderCart(){updateCounts();const entries=Object.entries(state.cart);if(!entries.length){$('#cartItems').innerHTML=`<div class="cart-empty">${icon('bag')}<h3>Room for something special.</h3><p>Your demo bag is empty. Take a look around.</p><button type="button" class="button primary" data-continue-shopping>Explore the marketplace ${icon('arrow')}</button></div>`;$('#cartFooter').hidden=true;return;}$('#cartFooter').hidden=false;$('#cartItems').innerHTML=entries.map(([id,qty])=>{const p=productById.get(id);return `<article class="cart-item"><div class="cart-item-art">${productArt(p)}</div><div class="cart-item-copy"><div class="cart-item-heading"><h3>${esc(p.name)}</h3><button type="button" class="remove-item" data-remove="${id}" aria-label="Remove ${esc(p.name)}">${icon('x')}</button></div><p>${money(p.price)} each · sample price</p><div class="cart-item-bottom"><div class="qty-control"><button type="button" data-qty-minus="${id}" aria-label="Decrease ${esc(p.name)} quantity">${icon('minus')}</button><span aria-label="Quantity ${qty}">${qty}</span><button type="button" data-qty-plus="${id}" aria-label="Increase ${esc(p.name)} quantity" ${qty>=MAX_QUANTITY?'disabled':''}>${icon('plus')}</button></div><span class="cart-line-price">${money(p.price*qty)}</span></div></div></article>`;}).join('');$('#cartFooter').innerHTML=`<div class="total-row"><span>Demo subtotal</span><strong>${money(subtotal())}</strong></div><div class="total-row minor"><span>Shipping & taxes</span><span>Not calculated in this demo</span></div><button type="button" class="button primary" id="previewCheckout">Preview checkout ${icon('arrow')}</button><p>No live payment. No actual order. All prices are illustrative.</p>`;}
  function renderDetail(id){const p=productById.get(id);if(!p)return;const saved=state.favorites.includes(id);$('#productDetail').innerHTML=`<div class="product-detail-grid"><div class="detail-art">${productArt(p)}<span>CONCEPT ILLUSTRATION · NOT A PRODUCT PHOTO</span></div><div class="detail-copy"><span class="eyebrow">${esc(p.categoryLabel)}</span><h2>${esc(p.name)}</h2><div class="detail-price">${money(p.price)} <span>DEMO PRICE</span></div><p>${esc(p.description)}</p><dl class="detail-specs"><div><dt>Weight</dt><dd>${esc(p.weight)}</dd></div><div><dt>Composition</dt><dd>${esc(p.purity)}</dd></div><div><dt>Catalog reference</dt><dd>${p.id.toUpperCase()}</dd></div><div><dt>Listing status</dt><dd>Fictional demo inventory</dd></div></dl><div class="detail-buy-row"><div class="qty-control"><button type="button" id="detailMinus" aria-label="Decrease product quantity" ${detailQuantity<=1?'disabled':''}>${icon('minus')}</button><span id="detailQuantity" aria-live="polite">${detailQuantity}</span><button type="button" id="detailPlus" aria-label="Increase product quantity" ${detailQuantity>=MAX_QUANTITY?'disabled':''}>${icon('plus')}</button></div><button type="button" class="button primary" id="detailAdd">Add to demo bag ${icon('bag')}</button></div><button type="button" class="detail-save" data-save="${id}" aria-pressed="${saved}">${icon('heart')}${saved?'Saved to your collection':'Save for a closer look'}</button><p class="detail-fineprint">Prices, artwork, and specifications are examples only. No authentication, availability, return, or investment claims are made.</p></div></div>`;}
  function showProduct(id){if(!productById.has(id))return;currentProductId=id;detailQuantity=1;renderDetail(id);openDialog('productDialog');}
  function syncFilterForm(){const input=$(`input[name="price"][value="${state.price}"]`);if(input)input.checked=true;$('#savedFilter').checked=state.savedOnly;}
  function showCheckout(){if(!cartCount())return;lastOrder=null;$('#checkoutTitle').textContent='One last look.';const lines=Object.entries(state.cart).map(([id,qty])=>{const p=productById.get(id);return `<div class="checkout-line"><div class="checkout-line-art">${productArt(p)}</div><div><h3>${esc(p.name)}</h3><p>Quantity ${qty} · sample inventory</p></div><span>${money(p.price*qty)}</span></div>`;}).join('');$('#checkoutContent').innerHTML=`<div class="checkout-lines">${lines}</div><div class="total-row total"><span>Demo subtotal</span><strong>${money(subtotal())}</strong></div><div class="total-row minor"><span>Shipping & taxes</span><span>Not calculated</span></div><div class="checkout-disclaimer">Completing this demonstration clears your demo bag and creates a local sample receipt. It does not submit an order, reserve goods, send email, or charge money.</div><button type="button" class="button primary full" id="completeDemoOrder">Complete demo — no charge ${icon('check')}</button>`;openDialog('checkoutDialog');}
  function completeDemo(){if(!cartCount())return;lastOrder={demo:true,orderId:`DEMO-${new Date().toISOString().slice(0,10).replaceAll('-','')}-${Math.random().toString(36).slice(2,7).toUpperCase()}`,createdAt:new Date().toISOString(),currency:'USD',items:Object.entries(state.cart).map(([id,quantity])=>({sku:id,name:productById.get(id).name,quantity,unitPriceCents:productById.get(id).price})),subtotalCents:subtotal(),shipping:null,taxes:null,paymentStatus:'NOT_CHARGED',fulfillmentStatus:'NOT_AN_ORDER',notice:'LOCAL DEMONSTRATION ONLY. Fictional inventory and prices. No goods purchased, no payment collected, no email sent.'};state.cart={};persist();updateCounts();$('#checkoutTitle').textContent='Demo complete.';$('#checkoutContent').innerHTML=`<div class="form-success"><span class="success-mark">${icon('check')}</span><h3>A preview, not a purchase.</h3><p>Your demo bag has been cleared. No order was submitted, no email was sent, and no money changed hands.</p><span class="receipt-number">${esc(lastOrder.orderId)}</span><button type="button" class="button primary" id="downloadReceipt">Download sample receipt ${icon('download')}</button><button type="button" class="text-link" data-continue-shopping>Back to the collection ${icon('arrow')}</button></div>`;}
  function downloadFile(filename,content,type='text/plain;charset=utf-8'){const blob=new Blob([content],{type});const url=URL.createObjectURL(blob);const anchor=document.createElement('a');anchor.href=url;anchor.download=filename;document.body.append(anchor);anchor.click();anchor.remove();setTimeout(()=>URL.revokeObjectURL(url),2000);}
  const policies={shipping:{title:'Shipping & returns.',body:'<p>This prototype does not accept orders or ship physical goods. Shipping charges, carriers, transit coverage, delivery timeframes, destination eligibility, and return policies have not been configured.</p><p>Before launch, the owner must publish reviewed terms for the actual product categories and selling channels, obtain appropriate insurance, and connect a checkout that calculates the applicable charges. Do not treat this placeholder as a shipping promise or return agreement.</p>'},privacy:{title:'Privacy & prototype terms.',body:'<p>This standalone prototype has no analytics, account registration, third-party scripts, or payment processing. It makes no external network requests for its storefront features. Bag contents and saved product references are stored in this browser when local storage is available.</p><p>The sample selling form and email signup do not transmit information. A selling inquiry can be downloaded as a local text file. Do not enter sensitive information. “Reset demo data” clears the stored demo bag and favorites.</p><p>This is not a live merchant agreement or a complete legal privacy policy. A deployed site may have separate hosting logs and services. The owner must publish policies matching the actual production infrastructure before accepting customer data or orders.</p>'}};

  document.addEventListener('click',event=>{
    const target=event.target instanceof Element?event.target.closest('button,a'):null;if(!target)return;
    if(target.hasAttribute('data-close')){closeDialogFrom(target);return;}
    if(target.dataset.open){event.preventDefault();openDialog(target.dataset.open);return;}
    if(target.dataset.policy){const policy=policies[target.dataset.policy];if(policy){$('#policyTitle').textContent=policy.title;$('#policyContent').innerHTML=policy.body;openDialog('policyDialog');}return;}
    if(target.dataset.category){chooseCategory(target.dataset.category);return;}
    if(target.dataset.categoryLink){chooseCategory(target.dataset.categoryLink);return;}
    if(target.dataset.product){showProduct(target.dataset.product);return;}
    if(target.dataset.save){toggleFavorite(target.dataset.save);return;}
    if(target.dataset.add){addToCart(target.dataset.add);return;}
    if(target.dataset.remove){delete state.cart[target.dataset.remove];persist();updateCounts();renderCart();return;}
    if(target.dataset.qtyMinus){changeQuantity(target.dataset.qtyMinus,-1);return;}
    if(target.dataset.qtyPlus){changeQuantity(target.dataset.qtyPlus,1);return;}
    if(target.hasAttribute('data-clear-saved')){state.savedOnly=false;renderCatalog();return;}
    if(target.hasAttribute('data-clear-price')){state.price='all';renderCatalog();return;}
    if(target.hasAttribute('data-continue-shopping')){closeDialogFrom(target);$('#marketplace').scrollIntoView({behavior:'smooth'});return;}
    switch(target.id){
      case'cartTrigger':openDialog('cartDialog');break;
      case'searchTrigger':$('#marketplace').scrollIntoView({behavior:'smooth'});$('#productSearch').focus({preventScroll:true});break;
      case'favoritesTrigger':state.savedOnly=true;state.category='all';state.price='all';state.search='';$('#productSearch').value='';renderCatalog();$('#marketplace').scrollIntoView({behavior:'smooth'});break;
      case'resetFilters':resetFilters();break;
      case'clearFilterForm':$('#filterForm').reset();break;
      case'previewCheckout':showCheckout();break;
      case'completeDemoOrder':completeDemo();break;
      case'downloadReceipt':if(lastOrder)downloadFile(`${lastOrder.orderId}.json`,JSON.stringify(lastOrder,null,2),'application/json');break;
      case'detailMinus':detailQuantity=Math.max(1,detailQuantity-1);renderDetail(currentProductId);$('#detailMinus').focus();break;
      case'detailPlus':detailQuantity=Math.min(MAX_QUANTITY,detailQuantity+1);renderDetail(currentProductId);$('#detailPlus').focus();break;
      case'detailAdd':addToCart(currentProductId,detailQuantity);break;
      case'downloadInquiry':if(lastInquiry)downloadFile('aldercrest-demo-inquiry.txt',lastInquiry);break;
      case'newInquiry':resetInquiry();$('#sellForm input[name="name"]').focus();break;
      case'resetDemo':if(window.confirm('Clear this browser’s demo bag, saved pieces, and filters?')){state.cart={};state.favorites=[];persist();resetFilters();notify('Demo bag, saved pieces, and filters reset.');}break;
    }
  });
  $('#productSearch').addEventListener('input',event=>{state.search=event.target.value;renderCatalog();});
  $('#sortSelect').addEventListener('change',event=>{state.sort=event.target.value;renderCatalog();});
  $('#filterForm').addEventListener('submit',event=>{event.preventDefault();state.price=new FormData(event.currentTarget).get('price')||'all';state.savedOnly=$('#savedFilter').checked;renderCatalog();$('#filterDialog').close();});
  $('#newsletterForm').addEventListener('submit',event=>{event.preventDefault();event.currentTarget.reset();notify('Signup preview complete. No email sent or subscription created.');});
  function resetInquiry(){lastInquiry='';$('#sellForm').reset();$('#sellForm').hidden=false;$('#sellSuccess').hidden=true;}
  $('#sellForm').addEventListener('submit',event=>{event.preventDefault();const form=new FormData(event.currentTarget);lastInquiry=`ALDERCREST RESERVE — DEMO SELLING INQUIRY\nLOCAL DRAFT ONLY. NOTHING HAS BEEN SENT.\n\nCreated: ${new Date().toISOString()}\nName: ${String(form.get('name')).trim()}\nEmail: ${String(form.get('email')).trim()}\nCategory: ${form.get('category')}\nNumber of pieces: ${form.get('quantity')}\n\nDescription:\n${String(form.get('description')).trim()}\n\nThis is a sample workflow. No valuation, purchase offer, upload, email, or merchant contact has occurred.\n`;$('#sellForm').hidden=true;$('#sellSuccess').hidden=false;$('#downloadInquiry').focus();});
  $('#sellDialog').addEventListener('close',resetInquiry);
  $$('dialog').forEach(dialog=>dialog.addEventListener('click',event=>{if(event.target!==dialog)return;const rect=dialog.getBoundingClientRect();if(event.clientX<rect.left||event.clientX>rect.right||event.clientY<rect.top||event.clientY>rect.bottom)dialog.close();}));
  document.addEventListener('keydown',event=>{const el=document.activeElement;if(event.key==='/'&&!event.ctrlKey&&!event.metaKey&&!event.altKey&&!el?.matches('input,textarea,select,[contenteditable="true"]')&&!$('dialog[open]')){event.preventDefault();$('#marketplace').scrollIntoView({behavior:'smooth'});$('#productSearch').focus({preventScroll:true});}});

  loadState();
  $('#heroArt').innerHTML=buildHeroArt();
  $('#sellArt').innerHTML=buildSellArt();
  initIcons();
  renderCatalog();
})();
